/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
/* Header for class codec_Codec */

#ifndef _Included_codec_Codec
#define _Included_codec_Codec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     codec_Codec
 * Method:    decode_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_codec_Codec_decode_1release
  (JNIEnv *, jclass);

/*
 * Class:     codec_Codec
 * Method:    decode_init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_codec_Codec_decode_1init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     codec_Codec
 * Method:    decode_frame
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_codec_Codec_decode_1frame
  (JNIEnv *, jclass, jbyteArray);

JNIEXPORT void JNICALL Java_codec_Codec_open_1file
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     codec_Codec
 * Method:    write_video
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_codec_Codec_write_1video
  (JNIEnv *, jclass, jbyteArray);

JNIEXPORT void JNICALL Java_codec_Codec_close_1file
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
